dependencies: invenio 3.4
rero/rero-ebooks pull request #43
Opened 2020-12-21 10:40 UTC by rerowep

* Upgrades to invenio 3.4.

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

2021-01-06 12:00 UTC, zannkukai approved these changes

2021-01-12 11:08 UTC, iGormilhit requested changes
Commit message proposition: `dependencies: upgrade invenio to 3.4`

2021-01-18 06:46 UTC, iGormilhit approved these changes

2021-01-26 07:04 UTC, jma approved these changes

2021-02-17 13:08 UTC, zannkukai approved these changes

2021-04-12 12:47 UTC, merged