dependencies: update the dependencies lock file
rero/rero-ebooks pull request #59
Opened 2022-04-25 11:59 UTC by rerowep

* Changes marshmallow to version > 3. Needs fixed invenio-oaiserver.
* Changes elastic search to version 7.16.3

Co-Authored-by: Peter Weber <peter.weber@rero.ch>dependencies: update

2022-04-26 04:56 UTC, Garfield-fr approved these changes

2022-04-27 07:14 UTC, zannkukai approved these changes

2022-05-02 09:34 UTC, BadrAly approved these changes

2022-05-11 09:13 UTC, jma requested changes
The changes seems not correspond to the commit message.

2022-05-11 09:13 UTC, jma commented on pytest.ini
> +addopts = --pydocstyle --doctest-glob="*.rst" --doctest-modules --cov=rero_ebooks --cov-report=term-missing --ignore=setup.py --ignore=docs/conf.py --color=yes
this is not in the commit message

2022-05-23 08:04 UTC, jma approved these changes

2022-07-27 14:57 UTC, merged